### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by vieirafrancisco** [svhenrique/projext-web-project#1]
Olá, @svhenrique. Tudo bem?

Teu projeto é bem legal e a descrição que você fez no `README` ficou bem bacana!
Só senti falta das URLs para pode utilizar as funcionalidades do sistema.

Vou deixar aqui algumas sugestões minhas de mudanças:

- Em vez de colocar os signals no `views.py` eu sugiro colocar em um arquivo `signals.py` ou em qualquer outro arquivo no diretório do app. Por que? Porque com o crescimento do projeto, muito provavelmente, você vai ter mais views e consequente mais signals. Daí ficaria muito mais complicado para gerenciar (buscar partes do código por exemplo).
- Cria um arquivo `env.example` ou `.env.example` ou qualquer outro nome. Para que você possa colocar as chaves do arquivo `.env` só que SEM OS VALORES, para que o usuário tenha um direcionamento das variáveis que têm. Você pode descrever no `README` como você fez, mas sugiro que você adicione esse arquivo para facilitar o uso.
- Você sugeriu criar um projeto para pegar a `SECRET_KEY`: `django-admin startproject projeto`. Porém tem uma função do django que gera para você (sem precisar criar outro projeto) `django.core.management.utils.get_random_secret_key()`. E também tem a opção de gerar essa chave em algum site na web.
OBS: Só tome cuidado quando você gera essas chaves em bancos de dados já populados. Porque o próprio django utiliza essas chaves para criptografia e gerenciamento de sessões (se não me engano).
- Sugiro você colocar a constante `DEBUG` do `settings.py` na variável de ambiente. Não é um dado sensível, porém ajuda na hora do deploy quando você quer alternar esse valor sem precisar mudar no arquivo.

Qualquer dúvida é só mandar por aqui.

**Comment by svhenrique** [comment]
Opa Francisco, beleza?

Adorei as dicas, foram muito esclarecedoras.

Eu pretendo terminar esse projeto com o tempo, estou aprendendo docker no momento e tentando adiciona-lo ao projeto, depois virá as urls e o front. Estou revendo as aulas gravadas  e elas são incríveis (próximo passo  é dominar o Django REST) .

Não enviei as atividades do curso pois pretendo aprender e aplicar os conceitos ensinados aos poucos, devido a correria do dia a dia não pude completar as atividades em tempo de curso, porém o projeto será finalizado com tudo ensinado.

Agradeço muito pelas aulas, elas foram incríveis. Sei que esse não é o lugar para isso, mas parabéns a todos da equipe!!👏 👏👏👏

**Comment by svhenrique** [comment]
Ajustes a serem feitos:

- [x] - Criar signals.py e adicionar os signals nele.

- [x] - Criar uma variável de ambiente env.example e colocar as chaves necessárias (sem os valores).

- [x] - Atualizar README para coletar SECRET_KEY com métodos sugeridos.

- [x] -  Por constante DEBUG dos settings.py na  variável de ambiente.

- [x] - Modificar README.md refletindo as alterações feitas.
